id: I1A1CCF41
legacy_id: P006672
ocr_import_info:
  bdrc_scan_id: W3916
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T22:44:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:14:35.911374+00:00'
last_modified: 2022-09-03 20:15:44.317739
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3916
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3916
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། པདྨ་རྣམ་རྒྱལ།
  author: ཞེ་ཆེན་རྒྱལ་ཚབ ༠༤་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.7781233154230637
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I2872:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2872
      total_pages: 614
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2872.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9470485507284553
    legacy_id: v002
  I2874:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2874
      total_pages: 518
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2874.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9446034883392157
    legacy_id: v004
  I2885:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2885
      total_pages: 638
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I2885.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9435992286710888
    legacy_id: v015
  I2889:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2889
      total_pages: 549
      volume_number: 19
      volume_pages_bdrc_intro: 0
    order: 19
    base_file: I2889.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.732617684115394
    legacy_id: v019
  I2884:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2884
      total_pages: 600
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I2884.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9469305083558366
    legacy_id: v014
  I2893:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2893
      total_pages: 2
      volume_number: 23
      volume_pages_bdrc_intro: 0
    order: 23
    base_file: I2893.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9444552596209114
    legacy_id: v023
  I2871:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2871
      total_pages: 766
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2871.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9475145699908433
    legacy_id: v001
  I2878:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2878
      total_pages: 616
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2878.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9465510666025856
    legacy_id: v008
  I2876:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2876
      total_pages: 472
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2876.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9473062084857807
    legacy_id: v006
  I2881:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2881
      total_pages: 724
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I2881.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9459689988992935
    legacy_id: v011
  I2886:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2886
      total_pages: 740
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I2886.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9401930565999742
    legacy_id: v016
  I2887:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2887
      total_pages: 533
      volume_number: 17
      volume_pages_bdrc_intro: 0
    order: 17
    base_file: I2887.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7599290523949774
    legacy_id: v017
  I2891:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2891
      total_pages: 2
      volume_number: 21
      volume_pages_bdrc_intro: 0
    order: 21
    base_file: I2891.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9424612468411756
    legacy_id: v021
  I2882:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2882
      total_pages: 830
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I2882.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9473151822034487
    legacy_id: v012
  I2888:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2888
      total_pages: 712
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I2888.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9443579834490898
    legacy_id: v018
  I2879:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2879
      total_pages: 683
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2879.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9454191103432379
    legacy_id: v009
  I2895:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2895
      total_pages: 710
      volume_number: 25
      volume_pages_bdrc_intro: 2
    order: 25
    base_file: I2895.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9432656896812669
    legacy_id: v025
  I2880:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2880
      total_pages: 1049
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I2880.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9421305247437702
    legacy_id: v010
  I2873:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2873
      total_pages: 606
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2873.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9459223368792858
    legacy_id: v003
  I2883:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2883
      total_pages: 556
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I2883.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9432943536233717
    legacy_id: v013
  I2890:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2890
      total_pages: 2
      volume_number: 20
      volume_pages_bdrc_intro: 0
    order: 20
    base_file: I2890.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9435396584136343
    legacy_id: v020
  I2892:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2892
      total_pages: 2
      volume_number: 22
      volume_pages_bdrc_intro: 0
    order: 22
    base_file: I2892.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.943617027807743
    legacy_id: v022
  I2877:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2877
      total_pages: 734
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2877.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9479423146981459
    legacy_id: v007
  I2894:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2894
      total_pages: 2
      volume_number: 24
      volume_pages_bdrc_intro: 0
    order: 24
    base_file: I2894.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9425918827089166
    legacy_id: v024
  I2875:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2875
      total_pages: 506
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2875.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9464077738882268
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
