id: I1A1CCF41
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:44:49+00:00'
last_modified: '2022-06-08T06:02:31.305898+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3916
  title: གསུང་འབུམ། པདྨ་རྣམ་རྒྱལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2B72:
      image_group_id: I2871
      title: ''
      total_pages: 766
      order: 1
      base_file: 2B72.txt
    A2E1:
      image_group_id: I2872
      title: ''
      total_pages: 614
      order: 2
      base_file: A2E1.txt
    464D:
      image_group_id: I2873
      title: ''
      total_pages: 606
      order: 3
      base_file: 464D.txt
    FCB0:
      image_group_id: I2874
      title: ''
      total_pages: 518
      order: 4
      base_file: FCB0.txt
    '2129':
      image_group_id: I2875
      title: ''
      total_pages: 506
      order: 5
      base_file: 2129.txt
    4C30:
      image_group_id: I2876
      title: ''
      total_pages: 472
      order: 6
      base_file: 4C30.txt
    82F5:
      image_group_id: I2877
      title: ''
      total_pages: 734
      order: 7
      base_file: 82F5.txt
    '8440':
      image_group_id: I2878
      title: ''
      total_pages: 616
      order: 8
      base_file: 8440.txt
    654F:
      image_group_id: I2879
      title: ''
      total_pages: 683
      order: 9
      base_file: 654F.txt
    BA82:
      image_group_id: I2880
      title: ''
      total_pages: 1049
      order: 10
      base_file: BA82.txt
    5FF1:
      image_group_id: I2881
      title: ''
      total_pages: 724
      order: 11
      base_file: 5FF1.txt
    14DF:
      image_group_id: I2882
      title: ''
      total_pages: 830
      order: 12
      base_file: 14DF.txt
    F554:
      image_group_id: I2883
      title: ''
      total_pages: 556
      order: 13
      base_file: F554.txt
    6CA1:
      image_group_id: I2884
      title: ''
      total_pages: 600
      order: 14
      base_file: 6CA1.txt
    3A68:
      image_group_id: I2885
      title: ''
      total_pages: 638
      order: 15
      base_file: 3A68.txt
    75FB:
      image_group_id: I2886
      title: ''
      total_pages: 740
      order: 16
      base_file: 75FB.txt
    A0A2:
      image_group_id: I2887
      title: ''
      total_pages: 533
      order: 17
      base_file: A0A2.txt
    43F5:
      image_group_id: I2888
      title: ''
      total_pages: 712
      order: 18
      base_file: 43F5.txt
    C88C:
      image_group_id: I2889
      title: ''
      total_pages: 549
      order: 19
      base_file: C88C.txt
    EAF4:
      image_group_id: I2890
      title: ''
      total_pages: 2
      order: 20
      base_file: EAF4.txt
    9D04:
      image_group_id: I2891
      title: ''
      total_pages: 2
      order: 21
      base_file: 9D04.txt
    77F5:
      image_group_id: I2892
      title: ''
      total_pages: 2
      order: 22
      base_file: 77F5.txt
    '5946':
      image_group_id: I2893
      title: ''
      total_pages: 2
      order: 23
      base_file: 5946.txt
    '7752':
      image_group_id: I2894
      title: ''
      total_pages: 2
      order: 24
      base_file: 7752.txt
    934A:
      image_group_id: I2895
      title: ''
      total_pages: 710
      order: 25
      base_file: 934A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
