id: P006672
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3916
  title: གསུང་འབུམ། པདྨ་རྣམ་རྒྱལ
  author: ''
  volumes:
    90f71c8304fa4ba2a97d38412ff36a05:
      image_group_id: I2871
      title: ''
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
    07257a4bb74947cfaac3c1f0e09e3d4f:
      image_group_id: I2872
      title: ''
      volume_number: 2
      total_pages: 614
      base_file: v002.txt
    16aadcacc81a43d9832df2925a009a68:
      image_group_id: I2873
      title: ''
      volume_number: 3
      total_pages: 606
      base_file: v003.txt
    d52d41b04ecf412faab7cde42e897ec2:
      image_group_id: I2874
      title: ''
      volume_number: 4
      total_pages: 518
      base_file: v004.txt
    9bbc87f4dd3f4447b8fbc253e102e5cc:
      image_group_id: I2875
      title: ''
      volume_number: 5
      total_pages: 506
      base_file: v005.txt
    a900baf5ca81449681f6670e2fd81b10:
      image_group_id: I2876
      title: ''
      volume_number: 6
      total_pages: 472
      base_file: v006.txt
    fcca61768df94742a0cd3213d11d2233:
      image_group_id: I2877
      title: ''
      volume_number: 7
      total_pages: 734
      base_file: v007.txt
    d4133c2ae5ed4d79b2e9f17ec6729e8d:
      image_group_id: I2878
      title: ''
      volume_number: 8
      total_pages: 616
      base_file: v008.txt
    40dc8ae582d244888d6d37001a83b9f4:
      image_group_id: I2879
      title: ''
      volume_number: 9
      total_pages: 683
      base_file: v009.txt
    c04028fd3c5542a4a78513b61ad90ca3:
      image_group_id: I2880
      title: ''
      volume_number: 10
      total_pages: 1049
      base_file: v010.txt
    d2a44879e509490aa22a60b522b9f4b6:
      image_group_id: I2881
      title: ''
      volume_number: 11
      total_pages: 724
      base_file: v011.txt
    40997aef80254f028e46cb3d0584c2b8:
      image_group_id: I2882
      title: ''
      volume_number: 12
      total_pages: 830
      base_file: v012.txt
    c021dfb4db4648779c8f58f47affb253:
      image_group_id: I2883
      title: ''
      volume_number: 13
      total_pages: 556
      base_file: v013.txt
    12192ae33226458c96efad2e10af566c:
      image_group_id: I2884
      title: ''
      volume_number: 14
      total_pages: 600
      base_file: v014.txt
    0a206793fbed453d8ce12c5c0d15ac9f:
      image_group_id: I2885
      title: ''
      volume_number: 15
      total_pages: 638
      base_file: v015.txt
    514705fed2aa46a89e6f2dd863930b30:
      image_group_id: I2886
      title: ''
      volume_number: 16
      total_pages: 740
      base_file: v024.txt
    9ba594ca0a02439289c51c15c95f9aac:
      image_group_id: I2887
      title: ''
      volume_number: 17
      total_pages: 533
      base_file: v017.txt
    4b0774811108455ebadf6d877a08344f:
      image_group_id: I2888
      title: ''
      volume_number: 18
      total_pages: 712
      base_file: v018.txt
    ebfd4a50246f4578a3d7653700652f5f:
      image_group_id: I2889
      title: ''
      volume_number: 19
      total_pages: 549
      base_file: v019.txt
    5034a45a09c34ea69558102ba975587a:
      image_group_id: I2890
      title: ''
      volume_number: 20
      total_pages: 2
    92e7526b1f744d6cb615efc24f3dc6f8:
      image_group_id: I2891
      title: ''
      volume_number: 21
      total_pages: 2
    7484f4c6c9ab45d5a88910867095bed0:
      image_group_id: I2892
      title: ''
      volume_number: 22
      total_pages: 2
    be1e80d4ece748ca89f01143d4a73ce5:
      image_group_id: I2893
      title: ''
      volume_number: 23
      total_pages: 2
    9f90445cc70c420d842e11303da21e79:
      image_group_id: I2894
      title: ''
      volume_number: 24
      total_pages: 2
    7c3f7890d7e647dabf85daa20f4869af:
      image_group_id: I2895
      title: ''
      volume_number: 25
      total_pages: 710
      base_file: v025.txt
